kitty_mod cmd+shift

font_family JetBrains Mono
font_size 14.0

background #24273a
foreground #cad3f5
cursor #f4dbd6
cursor_shape beam
cursor_blink_interval 0.5

color0  #494d64
color1  #ed8796
color2  #a6da95
color3  #eed49f
color4  #8aadf4
color5  #f5bde6
color6  #8bd5ca
color7  #b8c0e0
color8  #5b6078
color9  #ed8796
color10 #a6da95
color11 #eed49f
color12 #8aadf4
color13 #f5bde6
color14 #8bd5ca
color15 #cad3f5

tab_bar_style separator
tab_bar_align center
tab_separator " | "
tab_powerline_style slanted
active_tab_foreground   #181926
active_tab_background   #c6a0f6
active_tab_font_style   bold
inactive_tab_foreground #cad3f5
inactive_tab_background #1e2030
inactive_tab_font_style normal
tab_bar_background #181926

macos_titlebar_color background

map cmd+t new_tab_with_cwd
map kitty_mod+t new_tab_with_cwd

scrollback_pager nvim -R -M -c "lua require('kitty_pager')(INPUT_LINE_NUMBER, CURSOR_LINE, CURSOR_COLUMN)" -
