export ZSH="{{ home }}/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
  bgnotify
  vscode
)

source $ZSH/oh-my-zsh.sh

export TERM=xterm-256color
export EDITOR=vim

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias clipboard="xclip -selection clipboard"