#!/bin/bash

install_dependencies() {
    for repository in $(cat ./dependencies/repositories); do
        sudo add-apt-repository -y $repository
    done

    for package in $(cat ./dependencies/packages); do
        sudo apt install -y $package
    done
}

install_oh_my_zsh() {
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    git clone https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
    cp ./files/zshrc ~/.zshrc
}

install_chrome() {
    wget -O /tmp/google-chrome-stable.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo dpkg -i /tmp/google-chrome-stable.deb
    rm /tmp/google-chrome-stable.deb
    sudo apt install -y -f
}

install_vscode() {
    wget -O /tmp/vscode.deb https://vscode-update.azurewebsites.net/latest/linux-deb-x64/stable
    sudo dpkg -i /tmp/vscode.deb
    rm /tmp/vscode.deb
    sudo apt install -y -f
}

install_spotify() {
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
    echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
    sudo apt update
    sudo apt install spotify-client
}

install_postgres() {
    sudo apt install postgresql postgresql-contrib libpq-dev
    sudo -u postgres createuser -rds $USER
    createdb $USER

    sudo pip install setuptools
    sudo pip install pgcli
}

install_docker() {
    curl -sSL get.docker.io | sh
    sudo usermod -aG docker $USER
}

install_node() {
    sudo npm install -g n
    sudo n stable
}

copy_config_files() {
    mkdir ~/.config/terminator
    cp ./files/terminator ~/.config/terminator/config
    cp ./files/gitconfig ~/.gitconfig
}

setup_vim() {
    ln -s ~/.dotfiles/vimrc ~/.vimrc
}

setup_dconf() {
    dconf load /org/gnome/mutter/ < ./files/dconf-mutter
    dconf load /org/gnome/shell/ < ./files/dconf-shell
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['']"
}

setup_all() {
    install_dependencies

    install_oh_my_zsh
    install_chrome
    install_vscode
    install_spotify
    install_postgres
    install_docker
    install_node

    copy_config_files
    setup_vim
}

setup_all
